### PR TITLE
Allow only multiline_end_regexp

### PR DESCRIPTION
**Pull request by denniswebb**
This change makes specifying `multiline_start_regexp` optional.  The result is that all log messages that precede the message matching `multiline_end_regexp` are combined to make a single message.

This solves #42 whose use-case is the new docker log output for single-json being limited to 16k. All single/multi-line logs end with `\n`.  I see no other way of solving this currently with the way fluent-plugin-concat works.  Sure you could set `multiline_start_regexp=\{\` and `multiline_end_regexp=\.*\\n`, but there could be edge cases where lines in the middle begin with `{` but aren't the start of a new multiline.

Tests have been added to test this use-case.

### CODE REVIEW

**Comment by okkez** [comment]
Thank you for PR. I will check this PR later.

NOTE about CI failed:
positive look-behind operator does not work with Ruby 2.4.0 or earlier (maybe fixed in Onigmo 6.1.1).

```
ommit 5398ef4904fb49b1088a2578f9be4b3ab4164550
Author: naruse <naruse@b2dd03c8-39d4-4d8f-98ff-823fe69b080e>
Date:   Mon Mar 13 09:05:46 2017 +0000

    merge revision(s) 57603: [Backport #12997]

            Merge Onigmo 6.1.1

            * Support absent operator https://github.com/k-takata/Onigmo/issues/82
            * https://github.com/k-takata/Onigmo/blob/Onigmo-6.1.1/HISTORY

    git-svn-id: svn+ssh://ci.ruby-lang.org/ruby/branches/ruby_2_4@57957 b2dd03c8-39d4-4d8f-98ff-823fe69b080e

:100644 100644 1c0bc904e4dd2770b59abe6ea2dcbb22ff39f55c 9c0f48c4a04ff01dc1a759d67ccf8d99b9d04d3a M      NEWS
:040000 040000 618dcfb281b9d2b9e4bf8ae99bdf15b3713eaff8 21ae0862a2bcbdd8a86d84f031d90d3de4c8f776 M      include
:100644 100644 7ce5113985cb11d53c7ae5a4a75ac9a856c51d04 3b359801d5b6f6108ab1d8c680d8715b5582d53a M      regcomp.c
:100644 100644 ca09a7fcb3ab49ff8150dc0d901ebe1f73bdd842 16d62fdf4098c444a0a32fb7da65e0c61c77da40 M      regenc.c
:100644 100644 b27884b32c4827d430613577d924e1362cce9748 9e5f5597317c513a46713dc7a1c23279e91d769f M      regexec.c
:100644 100644 624deea8640150c21144e462177b0bf04a6f3939 a2f5bbba1d1f8ff8a901dca3416b29d5008dcffe M      regint.h
:100644 100644 0a3ed5228a82193c5033270fcf16204a03143ec1 1e0dfd99bb30703befc965f808e78b9d91683a99 M      regparse.c
:100644 100644 111a840b84a4078066442eeef5e019092d06ab92 888ebf4ce66d1cc7c0564fdb59ce9f272f28fc9f M      regparse.h
:100644 100644 39214c4744396e88db658726fc6ac91fe32de1cc c074da87e99dd292671435f87d8c0ed2be7c8dd2 M      version.h
```

**Comment by denniswebb** [comment]
Thanks for the tip on positive look-behind.  Ruby isn't my native language.

**Comment by denniswebb** [comment]
@okkez Thanks for the tip.  All tests are passing now.  We're actually using this in prod already to handle our data teams super large log lines.

**Comment by okkez** [comment]
Thank you for fixing test case!!

**Comment by okkez** [comment]
Released v2.2.0

**Pull request merged**
